version: '3.7'

services:
  # Add node
  node-service:
    container_name: node-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
